### ISSUE TITLE
[ch 9] later chapters overriding good url regex with bad one

### ISSUE THREAD

**Issue by hyperknot** [leifos/tango_with_django_book#154]
In the earlier chapters, we introduced the
```
(?P<category_name_slug>[\w\-]+)
```
regex which is working correctly together with the slug module.

However in later chapters, especially in chapter 9, we override those with the wrong pattern: 
```
(?P<category_name_slug>\w+)
```
The missing `-` means that the it's not possible to view "other-frameworks", nor will reverse lookup work at all.

I recommend doing a find-and-replace to correct the bad url to the good one all through the codebase.

**Comment by PramodBisht** [comment]
Fixed this on https://github.com/leifos/tango_with_django_book/pull/138

**Comment by leifos** [comment]
Thanks.
