### ISSUE TITLE
Ch 12.1 -Registration-Redux - urlpatterns update missing 'url' 

### ISSUE THREAD

**Issue by balurm** [leifos/tango_with_django_book#156]
The updated urlpatterns should read as
url(r'^accounts/', include('registration.backends.simple.urls')) 
instead of just 
(r'^accounts/', include('registration.backends.simple.urls'))

**Comment by PramodBisht** [comment]
fixed this issue on https://github.com/leifos/tango_with_django_book/pull/138

**Comment by leifos** [comment]
thanks!
