### ISSUE TITLE
Chapter 16, using {% url 'goto' %}?page_id={{page.id}} gives a url not matched/found error

### ISSUE THREAD

**Issue by jddantes** [leifos/tango_with_django_book#162]
Oddly, using page_id={{page.url}} or even page_id={{page.title}} are processed, and even handled (I initially used the url to identify the pages) correctly.

page_id=20 (some random number) gives the same url not matched/found error.

I've noticed that even manually typing http://localhost/rango/goto?page_id=20 would be turned into http://localhost/rango/goto/20 (dropping the GET parameter, thus leading to the url error.) Why is it like this?

**Comment by jddantes** [comment]
Turns out it was from leftover code, when I was using HttpResponseRedirect(page_id), with page_id representing the url.

**Comment by leifos** [comment]
:-)
