### ISSUE TITLE
Category slugs don't get updated when populating

### ISSUE THREAD

**Issue by pdehaye** [leifos/tango_with_django_book#194]
In Chapter 7, when introducing slugs, it says:
"Since the save method is called for each Category, the overrided save method will be executed, updating the slug field."
This refers to the populate script of Chapter 6, which in fact does not save each category. So the slugs don't get automatically updated.

**Comment by leifos** [comment]
Hi, yeah, as part of the exercise you need to update the population script to make sure it saves the category.

Actually, I have just re-written the population script and this section for version 1.9 - where I have already included the save :-)
