### ISSUE TITLE
Attribute Error: 'QuerySet' object has no attribute 'name'

### ISSUE THREAD

**Issue by nitin42** [leifos/tango_with_django_book#200]
I am not able to resolve this problem in Chapter 7.  Stack trace of the error:

/Users/nitini/tango/tango_with_django_project/rango/views.py in category
        context_dict['category_name'] = category.name 

The queryset is  "category = Category.objects.filter(slug=category_name_slug)".

Also when I use get() instead of filter(),  it returns more than one object. In my case it returns 3 objects!

Thanks!

**Comment by leifos** [comment]
Hi Nitin,

I think that
"category = Category.objects.filter(slug=category_name_slug)".

should be:

"category = Category.objects.get(slug=category_name_slug)".

see

https://github.com/leifos/tango_with_django_19/blob/master/code/tango_with_django_project/rango/views.py

Leif

**Comment by leifos** [comment]
Thanks!

**Comment by Letni1** [comment]
serializer = YourSerializer(yourqueryset, many=True)

**Comment by Abhishek12345679** [comment]
If you are using mongoDB Atlas with mongoengine
```python
owner = Owner.objects().get(Q(email=email))
```
or, just :

```python
owner = Owner.objects().get(email=email)
```
