### ISSUE TITLE
6.4.1. Setup Database and Create Superuser (1.7)

### ISSUE THREAD

**Issue by muppofmalice** [leifos/tango_with_django_book#95]
"If you have not done so already you first need to initial the database."
It should say initialize?

and

"If you rememnber in settings.py there was a list of INSTALLED_APPS, this initial call to migrate, creates the tables for the associated apps, i.e. auth, admin, etc."
should perhaps be
"If you remember in settings.py there was a list of INSTALLED_APPS; This initial call to migrate creates the tables for the associated apps, i.e. auth, admin, etc."

and

"python manage.py migrate" shouldn't be run first, it seems:

[root@localhost rango]# python ../manage.py migrate
Operations to perform:
  Apply all migrations: admin, contenttypes, auth, sessions
Running migrations:
  No migrations to apply.
  Your models have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
[root@localhost rango]# python ../manage.py makemigrations
Migrations for 'rango':
  0001_initial.py:
    - Create model Category
    - Create model Page
[root@localhost rango]# python ../manage.py migrate
Operations to perform:
  Apply all migrations: admin, rango, contenttypes, auth, sessions
Running migrations:
  Applying rango.0001_initial... OK
[root@localhost rango]#

**Comment by leifos** [comment]
Thanks!
